version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "danielcomeau"
    assignees:
      - "danielcomeau"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "danielcomeau"
    assignees:
      - "danielcomeau"
    commit-message:
      prefix: "ci"